# TO run the app do
# docker-compose -f docker-compose-dev.yml up --build

  version: "3.1"

services:
  database:
    build:
      context: ./database
    image: atsea_db
    environment:
      POSTGRES_USER: template_user
      POSTGRES_DB: template_app
    ports:
      - "5432:5432"
    networks:
      - back-tier
    secrets:
      - postgres_password

  appserver:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: atsea_app
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay